version: '3.8'

services:
  usuf-bot:
    container_name: usuf-bot
    build:
      context: .
    image: zalimannard/usuf-bot
    environment:
      - PREFIX=INSERT_PREFIX
      - TOKEN=INSERT_TOKEN
    volumes:
      - ./queues/:/opt/usuf-bot/queues/
    restart: unless-stopped
